import {
  LayoutDashboard,
  Building2,
  Receipt,
  CreditCard,
  CalendarClock,
  ScanLine,
  UserPlus,
  BarChart3,
  ScrollText,
  Trash2,
  ShieldCheck,
  ShieldPlus,
  Store,
  Users,
  UsersRound,
  Car,
  Gem,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { NavIcon } from '@/lib/nav'

export const NAV_ICONS: Record<NavIcon, LucideIcon> = {
  overview: LayoutDashboard,
  facilities: Building2,
  tariffs: Receipt,
  operatorPlans: CreditCard,
  driverPlans: Car,
  bookings: CalendarClock,
  scan: ScanLine,
  team: UsersRound,
  billing: Gem,
  operatorDirectory: Store,
  onboarding: UserPlus,
  analytics: BarChart3,
  audit: ScrollText,
  trash: Trash2,
  approvals: ShieldCheck,
  users: Users,
  admins: ShieldPlus,
}
